services:
  db:
    image: postgres:16
    container_name: cantinho_dona_maria_db
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dona_maria_123
      POSTGRES_DB: cantinho_dona_maria

    ports:
      - "5433:5432"

    volumes:
      - dados_postgres:/var/lib/postgresql/data

      # Rode os arquivos em ordem alfabética:
      - ./schema_dona_maria.sql:/docker-entrypoint-initdb.d/01_schema_dona_maria.sql

volumes:
  dados_postgres:
    driver: local
